###############################################################################
# Created by write_sdc
# Thu Sep  8 17:22:00 2022
###############################################################################
current_design execute
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name i_clk -period 10.0000 [get_ports {i_clk}]
set_clock_transition 0.1500 [get_clocks {i_clk}]
set_clock_uncertainty 0.2500 i_clk
set_propagated_clock [get_clocks {i_clk}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_alu_carry_en}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_alu_flags_ie}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_alu_mode[0]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_alu_mode[1]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_alu_mode[2]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_alu_mode[3]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_jump_cond_code[0]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_jump_cond_code[1]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_jump_cond_code[2]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_jump_cond_code[3]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_jump_cond_code[4]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_l_reg_sel[0]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_l_reg_sel[1]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_l_reg_sel[2]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_mem_access}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_mem_we}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_mem_width}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_pc_ie}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_pc_inc}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_r_bus_imm}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_r_reg_sel[0]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_r_reg_sel[1]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_r_reg_sel[2]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_rf_ie[0]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_rf_ie[1]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_rf_ie[2]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_rf_ie[3]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_rf_ie[4]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_rf_ie[5]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_rf_ie[6]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_rf_ie[7]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_sreg_irt}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_sreg_jal_over}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_sreg_load}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_sreg_store}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_sys}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_used_operands[0]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {c_used_operands[1]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_flush}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_imm[0]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_imm[10]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_imm[11]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_imm[12]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_imm[13]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_imm[14]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_imm[15]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_imm[1]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_imm[2]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_imm[3]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_imm[4]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_imm[5]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_imm[6]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_imm[7]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_imm[8]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_imm[9]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_irq}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_jmp_predict}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_mem_exception}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_next_ready}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_data[0]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_data[10]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_data[11]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_data[12]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_data[13]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_data[14]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_data[15]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_data[1]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_data[2]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_data[3]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_data[4]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_data[5]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_data[6]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_data[7]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_data[8]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_data[9]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_ie[0]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_ie[1]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_ie[2]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_ie[3]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_ie[4]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_ie[5]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_ie[6]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_ie[7]}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_rst}]
set_input_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_submit}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_pc[0]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_pc[10]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_pc[11]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_pc[12]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_pc[13]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_pc[14]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_pc[15]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_pc[1]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_pc[2]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_pc[3]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_pc[4]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_pc[5]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_pc[6]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_pc[7]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_pc[8]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_pc[9]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_r0[0]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_r0[10]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_r0[11]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_r0[12]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_r0[13]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_r0[14]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_r0[15]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_r0[1]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_r0[2]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_r0[3]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_r0[4]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_r0[5]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_r0[6]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_r0[7]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_r0[8]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {dbg_r0[9]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_addr[0]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_addr[10]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_addr[11]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_addr[12]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_addr[13]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_addr[14]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_addr[15]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_addr[1]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_addr[2]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_addr[3]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_addr[4]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_addr[5]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_addr[6]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_addr[7]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_addr[8]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_addr[9]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_c_data_page}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_c_instr_page}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_data[0]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_data[10]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_data[11]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_data[12]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_data[13]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_data[14]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_data[15]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_data[1]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_data[2]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_data[3]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_data[4]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_data[5]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_data[6]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_data[7]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_data[8]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_data[9]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_exec_pc[0]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_exec_pc[10]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_exec_pc[11]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_exec_pc[12]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_exec_pc[13]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_exec_pc[14]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_exec_pc[15]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_exec_pc[1]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_exec_pc[2]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_exec_pc[3]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_exec_pc[4]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_exec_pc[5]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_exec_pc[6]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_exec_pc[7]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_exec_pc[8]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_exec_pc[9]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_flush}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_icache_flush}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_mem_access}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_mem_we}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_mem_width}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_pc_update}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_ready}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_reg_ie[0]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_reg_ie[1]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_reg_ie[2]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_reg_ie[3]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_reg_ie[4]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_reg_ie[5]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_reg_ie[6]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_reg_ie[7]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_submit}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_addr[0]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_addr[10]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_addr[11]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_addr[12]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_addr[13]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_addr[14]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_addr[15]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_addr[1]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_addr[2]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_addr[3]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_addr[4]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_addr[5]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_addr[6]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_addr[7]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_addr[8]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_addr[9]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_data_o[0]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_data_o[10]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_data_o[11]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_data_o[12]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_data_o[13]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_data_o[14]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_data_o[15]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_data_o[1]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_data_o[2]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_data_o[3]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_data_o[4]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_data_o[5]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_data_o[6]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_data_o[7]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_data_o[8]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_data_o[9]}]
set_output_delay 2.0000 -clock [get_clocks {i_clk}] -add_delay [get_ports {sr_bus_we}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {o_c_data_page}]
set_load -pin_load 0.0334 [get_ports {o_c_instr_page}]
set_load -pin_load 0.0334 [get_ports {o_flush}]
set_load -pin_load 0.0334 [get_ports {o_icache_flush}]
set_load -pin_load 0.0334 [get_ports {o_mem_access}]
set_load -pin_load 0.0334 [get_ports {o_mem_we}]
set_load -pin_load 0.0334 [get_ports {o_mem_width}]
set_load -pin_load 0.0334 [get_ports {o_pc_update}]
set_load -pin_load 0.0334 [get_ports {o_ready}]
set_load -pin_load 0.0334 [get_ports {o_submit}]
set_load -pin_load 0.0334 [get_ports {sr_bus_we}]
set_load -pin_load 0.0334 [get_ports {dbg_pc[15]}]
set_load -pin_load 0.0334 [get_ports {dbg_pc[14]}]
set_load -pin_load 0.0334 [get_ports {dbg_pc[13]}]
set_load -pin_load 0.0334 [get_ports {dbg_pc[12]}]
set_load -pin_load 0.0334 [get_ports {dbg_pc[11]}]
set_load -pin_load 0.0334 [get_ports {dbg_pc[10]}]
set_load -pin_load 0.0334 [get_ports {dbg_pc[9]}]
set_load -pin_load 0.0334 [get_ports {dbg_pc[8]}]
set_load -pin_load 0.0334 [get_ports {dbg_pc[7]}]
set_load -pin_load 0.0334 [get_ports {dbg_pc[6]}]
set_load -pin_load 0.0334 [get_ports {dbg_pc[5]}]
set_load -pin_load 0.0334 [get_ports {dbg_pc[4]}]
set_load -pin_load 0.0334 [get_ports {dbg_pc[3]}]
set_load -pin_load 0.0334 [get_ports {dbg_pc[2]}]
set_load -pin_load 0.0334 [get_ports {dbg_pc[1]}]
set_load -pin_load 0.0334 [get_ports {dbg_pc[0]}]
set_load -pin_load 0.0334 [get_ports {dbg_r0[15]}]
set_load -pin_load 0.0334 [get_ports {dbg_r0[14]}]
set_load -pin_load 0.0334 [get_ports {dbg_r0[13]}]
set_load -pin_load 0.0334 [get_ports {dbg_r0[12]}]
set_load -pin_load 0.0334 [get_ports {dbg_r0[11]}]
set_load -pin_load 0.0334 [get_ports {dbg_r0[10]}]
set_load -pin_load 0.0334 [get_ports {dbg_r0[9]}]
set_load -pin_load 0.0334 [get_ports {dbg_r0[8]}]
set_load -pin_load 0.0334 [get_ports {dbg_r0[7]}]
set_load -pin_load 0.0334 [get_ports {dbg_r0[6]}]
set_load -pin_load 0.0334 [get_ports {dbg_r0[5]}]
set_load -pin_load 0.0334 [get_ports {dbg_r0[4]}]
set_load -pin_load 0.0334 [get_ports {dbg_r0[3]}]
set_load -pin_load 0.0334 [get_ports {dbg_r0[2]}]
set_load -pin_load 0.0334 [get_ports {dbg_r0[1]}]
set_load -pin_load 0.0334 [get_ports {dbg_r0[0]}]
set_load -pin_load 0.0334 [get_ports {o_addr[15]}]
set_load -pin_load 0.0334 [get_ports {o_addr[14]}]
set_load -pin_load 0.0334 [get_ports {o_addr[13]}]
set_load -pin_load 0.0334 [get_ports {o_addr[12]}]
set_load -pin_load 0.0334 [get_ports {o_addr[11]}]
set_load -pin_load 0.0334 [get_ports {o_addr[10]}]
set_load -pin_load 0.0334 [get_ports {o_addr[9]}]
set_load -pin_load 0.0334 [get_ports {o_addr[8]}]
set_load -pin_load 0.0334 [get_ports {o_addr[7]}]
set_load -pin_load 0.0334 [get_ports {o_addr[6]}]
set_load -pin_load 0.0334 [get_ports {o_addr[5]}]
set_load -pin_load 0.0334 [get_ports {o_addr[4]}]
set_load -pin_load 0.0334 [get_ports {o_addr[3]}]
set_load -pin_load 0.0334 [get_ports {o_addr[2]}]
set_load -pin_load 0.0334 [get_ports {o_addr[1]}]
set_load -pin_load 0.0334 [get_ports {o_addr[0]}]
set_load -pin_load 0.0334 [get_ports {o_data[15]}]
set_load -pin_load 0.0334 [get_ports {o_data[14]}]
set_load -pin_load 0.0334 [get_ports {o_data[13]}]
set_load -pin_load 0.0334 [get_ports {o_data[12]}]
set_load -pin_load 0.0334 [get_ports {o_data[11]}]
set_load -pin_load 0.0334 [get_ports {o_data[10]}]
set_load -pin_load 0.0334 [get_ports {o_data[9]}]
set_load -pin_load 0.0334 [get_ports {o_data[8]}]
set_load -pin_load 0.0334 [get_ports {o_data[7]}]
set_load -pin_load 0.0334 [get_ports {o_data[6]}]
set_load -pin_load 0.0334 [get_ports {o_data[5]}]
set_load -pin_load 0.0334 [get_ports {o_data[4]}]
set_load -pin_load 0.0334 [get_ports {o_data[3]}]
set_load -pin_load 0.0334 [get_ports {o_data[2]}]
set_load -pin_load 0.0334 [get_ports {o_data[1]}]
set_load -pin_load 0.0334 [get_ports {o_data[0]}]
set_load -pin_load 0.0334 [get_ports {o_exec_pc[15]}]
set_load -pin_load 0.0334 [get_ports {o_exec_pc[14]}]
set_load -pin_load 0.0334 [get_ports {o_exec_pc[13]}]
set_load -pin_load 0.0334 [get_ports {o_exec_pc[12]}]
set_load -pin_load 0.0334 [get_ports {o_exec_pc[11]}]
set_load -pin_load 0.0334 [get_ports {o_exec_pc[10]}]
set_load -pin_load 0.0334 [get_ports {o_exec_pc[9]}]
set_load -pin_load 0.0334 [get_ports {o_exec_pc[8]}]
set_load -pin_load 0.0334 [get_ports {o_exec_pc[7]}]
set_load -pin_load 0.0334 [get_ports {o_exec_pc[6]}]
set_load -pin_load 0.0334 [get_ports {o_exec_pc[5]}]
set_load -pin_load 0.0334 [get_ports {o_exec_pc[4]}]
set_load -pin_load 0.0334 [get_ports {o_exec_pc[3]}]
set_load -pin_load 0.0334 [get_ports {o_exec_pc[2]}]
set_load -pin_load 0.0334 [get_ports {o_exec_pc[1]}]
set_load -pin_load 0.0334 [get_ports {o_exec_pc[0]}]
set_load -pin_load 0.0334 [get_ports {o_reg_ie[7]}]
set_load -pin_load 0.0334 [get_ports {o_reg_ie[6]}]
set_load -pin_load 0.0334 [get_ports {o_reg_ie[5]}]
set_load -pin_load 0.0334 [get_ports {o_reg_ie[4]}]
set_load -pin_load 0.0334 [get_ports {o_reg_ie[3]}]
set_load -pin_load 0.0334 [get_ports {o_reg_ie[2]}]
set_load -pin_load 0.0334 [get_ports {o_reg_ie[1]}]
set_load -pin_load 0.0334 [get_ports {o_reg_ie[0]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_addr[15]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_addr[14]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_addr[13]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_addr[12]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_addr[11]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_addr[10]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_addr[9]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_addr[8]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_addr[7]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_addr[6]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_addr[5]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_addr[4]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_addr[3]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_addr[2]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_addr[1]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_addr[0]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_data_o[15]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_data_o[14]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_data_o[13]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_data_o[12]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_data_o[11]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_data_o[10]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_data_o[9]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_data_o[8]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_data_o[7]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_data_o[6]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_data_o[5]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_data_o[4]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_data_o[3]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_data_o[2]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_data_o[1]}]
set_load -pin_load 0.0334 [get_ports {sr_bus_data_o[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_alu_carry_en}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_alu_flags_ie}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_mem_access}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_mem_we}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_mem_width}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_pc_ie}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_pc_inc}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_r_bus_imm}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_sreg_irt}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_sreg_jal_over}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_sreg_load}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_sreg_store}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_sys}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_flush}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_irq}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_jmp_predict}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_mem_exception}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_next_ready}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_rst}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_submit}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_alu_mode[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_alu_mode[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_alu_mode[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_alu_mode[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_jump_cond_code[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_jump_cond_code[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_jump_cond_code[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_jump_cond_code[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_jump_cond_code[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_l_reg_sel[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_l_reg_sel[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_l_reg_sel[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_r_reg_sel[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_r_reg_sel[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_r_reg_sel[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_rf_ie[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_rf_ie[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_rf_ie[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_rf_ie[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_rf_ie[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_rf_ie[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_rf_ie[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_rf_ie[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_used_operands[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {c_used_operands[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_imm[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_imm[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_imm[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_imm[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_imm[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_imm[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_imm[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_imm[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_imm[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_imm[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_imm[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_imm[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_imm[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_imm[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_imm[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_imm[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_data[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_data[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_data[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_data[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_data[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_data[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_data[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_data[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_data[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_data[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_data[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_data[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_data[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_data[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_data[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_data[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_ie[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_ie[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_ie[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_ie[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_ie[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_ie[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_ie[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_ie[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_fanout 10.0000 [current_design]
